# Generated by Django 5.1 on 2024-09-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
