# Generated by Django 5.1 on 2024-09-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0002_alter_dietplan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='image',
            field=models.ImageField(upload_to='dietimages'),
        ),
    ]
